apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-backend
  namespace: calorie-chronicle
  labels:
    app: calorie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calorie-backend
  template:
    metadata:
      labels:
        app: calorie-backend
    spec:
      containers:
      - name: backend
        image: adawy123/calorie-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: MONGODB_URI
          # The URI is constructed to include 'root' and $(MONGO_PASSWORD)
          value: "mongodb://root:$(MONGO_PASSWORD)@mongodb:27017/calorieapp"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: PORT
          value: "5000"
        - name: MONGO_PASSWORD # This pulls the actual password from the Secret.
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"