apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-frontend
  namespace: calorie-chronicle
  labels:
    app: calorie-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calorie-frontend
  template:
    metadata:
      labels:
        app: calorie-frontend
    spec:
      containers:
      - name: frontend
        image: adawy123/calorie-frontend:latest.v1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_API_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"