apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: calorie-chronicle
data:
  NODE_ENV: "production"
  FRONTEND_URL: "http://calorie-frontend:80"
  BACKEND_URL: "http://calorie-backend:5000"
  MONGODB_URI: "mongodb://mongodb:27017/calorieapp"
  
  # هذا المفتاح هو الذي يجب أن يتطابق مع ما يتوقعه Deployment
  VITE_API_URL: "http://calorie-backend:5000" # <--- تم تعديل الاسم هنا